* sync rsync with main arch

diff --git a/rsync/PKGBUILD b/rsync/PKGBUILD
--- a/rsync/PKGBUILD
+++ b/rsync/PKGBUILD
@@ -2,22 +2,23 @@
 
 pkgname=rsync
 pkgver=3.1.3
-pkgrel=1
+pkgrel=2
 pkgdesc="A file transfer program to keep remote files in sync"
-arch=('x86_64' 'powerpc64le')
+arch=(x86_64 powerpc64le)
 url="https://rsync.samba.org/"
 license=('GPL3')
 depends=('perl' 'popt' 'acl')
 backup=('etc/rsyncd.conf' 'etc/xinetd.d/rsync')
 install=rsync.install
 validpgpkeys=('0048C8B026D4C96F0E589C2F6C859FB14B96A8C5') # Wayne Davison <wayned@users.sourceforge.net>
-source=("https://rsync.samba.org/ftp/rsync/src/$pkgname-$pkgver.tar.gz"
+source=("https://rsync.samba.org/ftp/rsync/src/$pkgname-$pkgver.tar.gz"{,.asc}
         'rsyncd.conf'
         'rsync.xinetd'
         'rsyncd.service'
         'rsyncd.socket'
         'rsyncd@.service')
 sha256sums=('55cc554efec5fdaad70de921cd5a5eeb6c29a95524c715f3bbf849235b0800c0'
+            'SKIP'
             '733ccb571721433c3a6262c58b658253ca6553bec79c2bdd0011810bb4f2156b'
             'da0ec9ce07bf2edafbc8e44020da29a58038b00c3048a22de57017c56318a767'
             '6ad010a1f85f5637bdd0972403c032ca30d71608a36943c71c34ba1c5b463cd6'
@@ -32,23 +33,30 @@ build() {
 	./configure --prefix=/usr \
 		--with-included-popt=no \
 		--with-included-zlib=yes \
-		--disable-debug \
-		--build=$CHOST
+		--disable-debug --build=${CHOST}
 	make
 }
 
 check() {
 	cd "$srcdir/$pkgname-$pkgver"
+
+	# rsync fails with xattr on btrfs...
+	if [ "$(stat --file-system --printf=%T .)" = "btrfs" ]; then
+		echo "Test is known to fail on btrfs..." >&2
+		exit 1
+	fi
+
 	make test
 }
 
 package() {
 	cd "$srcdir/$pkgname-$pkgver"
+
 	make DESTDIR="$pkgdir" install
-	install -Dm644 ../rsyncd.conf "$pkgdir/etc/rsyncd.conf"
-	install -Dm644 ../rsync.xinetd "$pkgdir/etc/xinetd.d/rsync"
-	install -Dm644 ../rsyncd.service "$pkgdir/usr/lib/systemd/system/rsyncd.service"
-	install -m644 ../rsyncd.socket "$pkgdir/usr/lib/systemd/system/rsyncd.socket"
-	install -m644 ../rsyncd@.service "$pkgdir/usr/lib/systemd/system/rsyncd@.service"
-	install -Dm755 support/rrsync "$pkgdir/usr/lib/rsync/rrsync"
+	install -Dm0644 ../rsyncd.conf "$pkgdir/etc/rsyncd.conf"
+	install -Dm0644 ../rsync.xinetd "$pkgdir/etc/xinetd.d/rsync"
+	install -Dm0644 ../rsyncd.service "$pkgdir/usr/lib/systemd/system/rsyncd.service"
+	install -m0644 ../rsyncd.socket "$pkgdir/usr/lib/systemd/system/rsyncd.socket"
+	install -m0644 ../rsyncd@.service "$pkgdir/usr/lib/systemd/system/rsyncd@.service"
+	install -Dm0755 support/rrsync "$pkgdir/usr/lib/rsync/rrsync"
 }
