* update grpc to 1.80.0-1

diff --git a/grpc/PKGBUILD b/grpc/PKGBUILD
--- a/grpc/PKGBUILD
+++ b/grpc/PKGBUILD
@@ -7,11 +7,13 @@
 pkgbase='grpc'
 pkgname=('grpc' 'python-grpcio' 'python-grpcio-tools' 'php-grpc' 'php-legacy-grpc')
 [ "${CARCH}" == 'x86_64' ] && pkgname+=('grpc-cli')
-pkgver=1.76.0
+pkgver=1.80.0
 _gtestver=2dd1c131950043a8ad5ab0d2dda0e0970596586a
-pkgrel=4
+pkgrel=1
+_protobuf_ver=34.1
 pkgdesc="High performance, open source, general RPC framework that puts mobile and HTTP/2 first."
-arch=(x86_64 powerpc64le powerpc64 powerpc espresso)
+#arch=(x86_64 powerpc64le powerpc64 powerpc espresso)
+arch=(powerpc espresso)
 url='https://grpc.io'
 license=('Apache-2.0')
 makedepends=(
@@ -26,6 +28,7 @@ makedepends=(
   'php'
   'php-legacy'
   'protobuf'
+  'cython'
   'python-build'
   'python-installer'
   'python-setuptools'
@@ -35,11 +38,15 @@ makedepends=(
 )
 source=("https://github.com/grpc/grpc/archive/v$pkgver/$pkgbase-$pkgver.tar.gz"
         "https://github.com/google/googletest/archive/$_gtestver/googletest-$_gtestver.tar.gz"
-        php-8.5.patch
-        grpc-no-sse2-on-unsupported-isa.patch)
-sha256sums=('0af37b800953130b47c075b56683ee60bdc3eda3c37fc6004193f5b569758204'
+        "https://github.com/protocolbuffers/protobuf/archive/v${_protobuf_ver}/protobuf-${_protobuf_ver}.tar.gz"
+        "protobuf-34-build-fix.patch"
+        "fix-python-system-abseil.patch"
+        "grpc-no-sse2-on-unsupported-isa.patch")
+sha256sums=('38f58596277fa632064cc0719b9ece4381c8c77461cb51e9b66ca149574b7865'
             '31bf78bd91b96dd5e24fab3bb1d7f3f7453ccbaceec9afb86d6e4816a15ab109'
-            'a2b71c06347550260e5cffeb803a0737089ddadcd629643bf8dfdf8e71e6e4cc'
+            'a83103b7ed3afaeedee9a212c8f65825444f58144f5e075b73c83f2b4ff27b62'
+            '2c126e40c54bdc88ab57fad12cbd860fc999aceb0e2787263edcbf024097ecec'
+            '24a8dc761deff4a39b5fc9a7fb2b65c049e600b14c548a28f52376b98c456a7e'
             '7151a85112baa206fdb3764c01671d0b0193d4e39bfb95139b8b5676df5ead76')
 
 MYARCH=${CARCH}
@@ -50,11 +57,15 @@ esac
 prepare() {
   cd "$srcdir/$pkgbase-$pkgver"
 
+  patch -p1 -i "$srcdir/protobuf-34-build-fix.patch"
+  patch -p1 -i "$srcdir/fix-python-system-abseil.patch"
+  patch -p1 -i "$srcdir/grpc-no-sse2-on-unsupported-isa.patch"
+
   ln -sf "$srcdir/googletest-$_gtestver/"{googlemock,googletest} \
     third_party/googletest
 
   # CMake only downloads third party depends when folder does not exist
-  rmdir third_party/{envoy-api,xds,googleapis,protoc-gen-validate}
+  rmdir third_party/{cel-spec,envoy-api,xds,googleapis,protoc-gen-validate}
 
   cp -a src/php{,-legacy}
 
@@ -63,25 +74,32 @@ prepare() {
       -e '/^CC_FILES=\[/,/\]/{/^CC_FILES=\[/n;/\]/!d;}' \
       -e '/^CC_INCLUDES=\[/,/\]/{/^CC_INCLUDES=\[/n;/\]/!d;}' \
       -e "s@^(PROTO_INCLUDE=')[^']+'@\1/usr/include'@" \
+      -e "s@^(\s*').*/(google/protobuf/.*\.proto',?)\$@\1\2@" \
       -e '/^PROTOBUF_SUBMODULE_VERSION=/d' \
       tools/distrib/python/grpcio_tools/protoc_lib_deps.py
   ln -s ../../../.. tools/distrib/python/grpcio_tools/grpc_root
 
-  patch -Np1 -i ${srcdir}/php-8.5.patch
-  patch -Np1 -i ${srcdir}/grpc-no-sse2-on-unsupported-isa.patch
+  # relax cython version requirement
+  sed 's/[Cc]ython==/cython>=/' -i pyproject.toml tools/distrib/python/grpcio_tools/pyproject.toml
 }
 
 build() {
-  cd "$srcdir/$pkgbase-$pkgver"
+  # Workaround for protobuf 34.0+ until https://github.com/grpc/grpc/issues/41755 has been fixed.
+  if [[ "$(pacman -Q protobuf | grep -Po '[0-9.]+(?=-)')" != "$_protobuf_ver" ]]; then
+    echo 'error: protobuf version mismatch, please update $_protobuf_ver in the PKGBUILD' >&2
+    exit 1
+  fi
+  export CXXFLAGS+=" -isystem${srcdir}/protobuf-${_protobuf_ver}/src"
 
   case "${CARCH}" in
     powerpc) export CXXFLAGS+=" -latomic" ;;
     x86_64) _cmake_options=(-DgRPC_BUILD_TESTS=ON)  ;;
   esac
 
+  cd "$srcdir/$pkgbase-$pkgver"
   cmake -Bbuild \
     -DCMAKE_BUILD_TYPE=None \
-    -DCMAKE_CXX_FLAGS="${CXXFLAGS} -DNDEBUG -Wno-attributes -Wno-deprecated-declarations -Wno-return-type -Wno-non-virtual-dtor" \
+    -DCMAKE_CXX_FLAGS="${CXXFLAGS} -DNDEBUG -trigraphs -Wno-attributes -Wno-deprecated-declarations -Wno-return-type -Wno-non-virtual-dtor" \
     -DgRPC_INSTALL=ON \
     -DBUILD_SHARED_LIBS=ON \
     -DCMAKE_CXX_STANDARD=17 \
@@ -154,7 +172,7 @@ check() {
 }
 
 package_grpc() {
-  depends=('glibc' 'gcc-libs' 'zlib' 'systemd-libs' 'c-ares' 'protobuf' 'openssl' 're2' 'abseil-cpp')
+  depends=('glibc' 'libgcc' 'zlib' 'systemd-libs' 'c-ares' 'protobuf' 'openssl' 're2' 'abseil-cpp')
   provides=(
     'libupb.so'
     'libgrpcpp_channelz.so'
@@ -179,7 +197,8 @@ package_python-grpcio() {
   pkgdesc='Python language bindings for grpc, remote procedure call (RPC) framework'
   depends=(
     'glibc'
-    'gcc-libs'
+    'libgcc'
+    'libstdc++'
     'zlib'
     'openssl'
     'c-ares'
@@ -197,7 +216,7 @@ package_python-grpcio() {
 
 package_python-grpcio-tools() {
   pkgdesc='Python protobuf generator for GRPC'
-  depends=('glibc' 'gcc-libs' 'protobuf' 'python' 'python-setuptools' 'python-protobuf')
+  depends=('glibc' 'libgcc' 'libstdc++' 'protobuf' 'python' 'python-setuptools' 'python-protobuf')
 
   cd "$srcdir/$pkgbase-$pkgver"
   install -Dm644 LICENSE "$pkgdir"/usr/share/licenses/$pkgname/LICENSE
@@ -208,7 +227,7 @@ package_python-grpcio-tools() {
 
 package_php-grpc() {
   pkgdesc='gRPC module for PHP'
-  depends=('glibc' 'gcc-libs' 'grpc' 'php')
+  depends=('glibc' 'libstdc++' 'grpc' 'php')
   backup=('etc/php/conf.d/grpc.ini')
 
   # Install PHP extension.
@@ -225,7 +244,7 @@ package_php-grpc() {
 
 package_php-legacy-grpc() {
   pkgdesc='gRPC module for PHP Legacy'
-  depends=('glibc' 'gcc-libs' 'grpc' 'php-legacy')
+  depends=('glibc' 'libstdc++' 'grpc' 'php-legacy')
   backup=('etc/php-legacy/conf.d/grpc.ini')
 
   # Install PHP extension.
@@ -242,7 +261,7 @@ package_php-legacy-grpc() {
 
 package_grpc-cli() {
   pkgdesc='gRPC protocol buffers cli'
-  depends=('glibc' 'gcc-libs' 'grpc' 'protobuf' 'abseil-cpp')
+  depends=('glibc' 'libgcc' 'libstdc++' 'grpc' 'protobuf' 'abseil-cpp')
 
   cd "$srcdir/$pkgbase-$pkgver"
   install -dm0755 "$pkgdir/usr/lib"
