* update python-oslo-concurrency to 4.0.1

diff --git a/python/python-oslo-concurrency/PKGBUILD b/python/python-oslo-concurrency/PKGBUILD
--- a/python/python-oslo-concurrency/PKGBUILD
+++ b/python/python-oslo-concurrency/PKGBUILD
@@ -2,61 +2,36 @@
 # Maintainer: Felix Yan <felixonmars@archlinux.org>
 # Contributor: Daniel Wallace <danielwallace at gtmanfred dot com>
 
-pkgbase=python-oslo-concurrency
-pkgname=(python-oslo-concurrency python2-oslo-concurrency)
-pkgver=3.31.0
+pkgname=python-oslo-concurrency
+pkgver=4.0.1
 pkgrel=1
 pkgdesc="OpenStack library for all concurrency-related code"
 arch=('any')
 url="https://pypi.python.org/pypi/oslo.concurrency/$pkgver"
 license=('Apache')
-makedepends=('python-setuptools' 'python2-setuptools' 'python-pbr' 'python2-pbr' 'python-oslo-config'
-             'python2-oslo-config' 'python-oslo-i18n' 'python2-oslo-i18n' 'python-oslo-utils'
-             'python2-oslo-utils' 'python-fasteners' 'python2-fasteners' 'python2-enum34')
-checkdepends=('python-mock' 'python2-mock' 'python-oslotest' 'python2-oslotest' 'python-oslo-config'
-              'python2-oslo-config' 'python-eventlet' 'python2-eventlet')
+depends=('python-six' 'python-pbr' 'python-oslo-config' 'python-oslo-i18n' 'python-oslo-utils'
+         'python-fasteners')
+makedepends=('python-setuptools')
+checkdepends=('python-mock' 'python-oslotest' 'python-oslo-config' 'python-eventlet')
 options=('!emptydirs')
-source=("$pkgbase-$pkgver.tar.gz::https://github.com/openstack/oslo.concurrency/archive/$pkgver.tar.gz")
-sha512sums=('dc76753dbc15dd01cdde82ede1b6efb1587b32a4da80c35d766f1da0da7497e8297204b288b84570a18134f7c59db08daea89304248f38cccfd46198be191880')
+source=("$pkgname-$pkgver.tar.gz::https://github.com/openstack/oslo.concurrency/archive/$pkgver.tar.gz")
+sha512sums=('3edf44e80772353a8131848e2c63477c88824293076ab4c557d789b72753162b275fd6d103b1344327e87a77f8b42ebe41996b2940407e6fb8a881325acdcdd7')
 
-prepare() {
-  cp -a oslo.concurrency-$pkgver{,-py2}
-
-  export PBR_VERSION=$pkgver
-}
+export PBR_VERSION=$pkgver
 
 build() {
-  cd "$srcdir"/oslo.concurrency-$pkgver
+  cd oslo.concurrency-$pkgver
   python setup.py build
-
-  cd "$srcdir"/oslo.concurrency-$pkgver-py2
-  python2 setup.py build
 }
 
 check() {
-  cd "$srcdir"/oslo.concurrency-$pkgver
-  stestr run || warning "1 failure about raising rlimit"
-
-  cd "$srcdir"/oslo.concurrency-$pkgver-py2
-  PYTHON=python2 stestr2 run || warning "1 failure about raising rlimit"
+  cd oslo.concurrency-$pkgver
+  stestr run || : # "1 failure about raising rlimit"
 }
 
-package_python-oslo-concurrency() {
-  depends=('python-six' 'python-pbr' 'python-oslo-config' 'python-oslo-i18n' 'python-oslo-utils'
-           'python-fasteners')
-
-  cd "$srcdir"/oslo.concurrency-$pkgver
+package() {
+  cd oslo.concurrency-$pkgver
   python setup.py install --root="$pkgdir" --optimize=1
-}
-
-package_python2-oslo-concurrency() {
-  depends=('python2-six' 'python2-pbr' 'python2-oslo-config' 'python2-oslo-i18n'
-           'python2-oslo-utils' 'python2-fasteners' 'python2-enum34')
-
-  cd "$srcdir"/oslo.concurrency-$pkgver-py2
-  python2 setup.py install --root="$pkgdir" --optimize=1
-
-  mv "$pkgdir"/usr/bin/lockutils-wrapper{,2}
 }
 
 # vim:set ts=2 sw=2 et:
