* update aarch64-linux-gnu-binutils to 2.39-2

diff --git a/cross-compilers/aarch64-linux-gnu-binutils/PKGBUILD b/cross-compilers/aarch64-linux-gnu-binutils/PKGBUILD
--- a/cross-compilers/aarch64-linux-gnu-binutils/PKGBUILD
+++ b/cross-compilers/aarch64-linux-gnu-binutils/PKGBUILD
@@ -1,77 +1,71 @@
 # POWER Maintainer: Alexander Baldeck <alex.bldck@gmail.com>
-# Maintainer: Felix Yan <felixonmars@archlinux.org>
-# Maintainer: Alexander F. Rødseth <xyproto@archlinux.org>
-# Contributor: Emil Renner Berthing <aur@esmil.dk>
+# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>
 
 _target=aarch64-linux-gnu
 pkgname=$_target-binutils
-pkgver=2.38
-pkgrel=1
-pkgdesc='Assemble and manipulate binary and object files for 32-bit and 64-bit RISC-V'
-arch=(x86_64 powerpc64le powerpc riscv64)
-url='https://gnu.org/software/binutils/'
+pkgver=2.39
+pkgrel=2
+pkgdesc='A set of programs to assemble and manipulate binary and object files for the ARM64 target'
+arch=(x86_64 powerpc64le powerpc64 powerpc riscv64)
+url='https://www.gnu.org/software/binutils/'
 license=(GPL)
-makedepends=(setconf)
-source=("https://ftp.gnu.org/gnu/binutils/binutils-$pkgver.tar.xz"
-        gold-warn-unsupported.patch
-        fix-incorrect-undefined-symbol.patch
-        "binutils-pr28733.patch::https://sourceware.org/git/?p=binutils-gdb.git;a=patch;h=e4028336b19998e74a51dd0918a8b3922e08a537;hp=df0a549ebdae74ef9d233243b869d424e6a33c73")
-sha512sums=('8bf0b0d193c9c010e0518ee2b2e5a830898af206510992483b427477ed178396cd210235e85fd7bd99a96fc6d5eedbeccbd48317a10f752b7336ada8b2bb826d'
-            '5d827b349b4456f8314776f1545396945c751b822a77604157b3fe436e5ff82bb313af3a215c99fd9d1f1f8ebb9f92033cc1a4968e35734619ad28b9bb3839a7'
-            '36da578519db4665f959a64813173ecbf3f999bc6b3acfb216e24d73a617ded22202e08915d2fa4c86b46c627127bc6e22e6dba07ce89588c0da7771c6f34a58'
-            '243d177b01174cdafd87ba2df0b7dd982fbaf5502a35a5ebd96ede6a606db79c2f331da336e009c37a72dd4bbab4624386caa8e32632a1ce8d36a549fbf48b82')
+depends=(zlib libelf)
+source=(https://ftp.gnu.org/gnu/binutils/binutils-$pkgver.tar.bz2{,.sig})
+sha1sums=('d9028547385694d61d98fb4e2882a2b9c40ce7e9'
+          'SKIP')
+sha256sums=('da24a84fef220102dd24042df06fdea851c2614a5377f86effa28f33b7b16148'
+            'SKIP')
+validpgpkeys=('3A24BC1E8FB409FA9F14371813FCEF89DD9E3C4F') # Nick Clifton (Chief Binutils Maintainer) <nickc@redhat.com>
 
 prepare() {
-  cd "binutils-$pkgver"
-  # Creds @Fedora
-  # Change the gold configuration script to only warn about
-  # unsupported targets.  This allows the binutils to be built with
-  # BPF support enabled.
-  patch -Np1 -i "${srcdir}"/gold-warn-unsupported.patch
-
-  # fix incorrect "undefined reference" errors
-  # https://sourceware.org/bugzilla/show_bug.cgi?id=28879
-  patch -Np1 -i "${srcdir}"/fix-incorrect-undefined-symbol.patch
-
-  # riscv64: PR28733, add missing extension info to 'unrecognized opcode' error
-  patch -Np1 -i "${srcdir}"/binutils-pr28733.patch
-
-  setconf libiberty/configure ac_cpp "'\$CPP \$CPPFLAGS -O2'"
+  cd binutils-$pkgver
+  sed -i "/ac_cpp=/s/\$CPPFLAGS/\$CPPFLAGS -O2/" libiberty/configure
 }
 
 build() {
-  cd "binutils-$pkgver"
+  cd binutils-$pkgver
 
-  unset CPPFLAGS
-  ./configure \
-    --disable-nls \
-    --enable-deterministic-archives \
-    --enable-gold \
-    --enable-ld=default \
-    --enable-multilib \
-    --enable-plugins \
-    --prefix=/usr \
-    --target=$_target \
-    --with-gnu-as \
-    --with-gnu-ld \
-    --with-sysroot=/usr/$_target \
-    --with-system-zlib
+  if [ "${CARCH}" != "i686" ];
+  then
+    # enabling gold linker at i686 makes the install fail
+    enable_gold='--enable-gold'
+  fi
+
+  ./configure --target=$_target \
+              --with-sysroot=/usr/$_target \
+              --prefix=/usr \
+              --disable-multilib \
+              --with-gnu-as \
+              --with-gnu-ld \
+              --disable-nls \
+              --enable-ld=default \
+              $enable_gold \
+              --enable-plugins \
+              --enable-deterministic-archives
+
   make
 }
 
 check() {
-  # * Unset LDFLAGS as testsuite makes assumptions about which ones are active.
-  # * Do not abort on errors - manually check log files.
-  make -C "binutils-$pkgver" LDFLAGS="" -k check
+  cd binutils-$pkgver
+
+  # unset LDFLAGS as testsuite makes assumptions about which ones are active
+  # do not abort on errors - manually check log files
+  make -k LDFLAGS="" check || true
 }
 
 package() {
-  make -C "binutils-$pkgver" DESTDIR="$pkgdir" install
+  cd binutils-$pkgver
+
+  make DESTDIR="$pkgdir" install
+
+  # Remove file conflicting with host binutils and manpages for MS Windows tools
+  rm "$pkgdir"/usr/share/man/man1/$_target-{dlltool,windres,windmc}*
+  rm "$pkgdir"/usr/lib/bfd-plugins/libdep.so
+  rm -f "$pkgdir"/usr/etc/gprofng.rc
+  rm -rf "$pkgdir"/usr/include
+  rm -rf "$pkgdir"/usr/lib/gprofng/
 
   # Remove info documents that conflict with host version
-  rm -r "$pkgdir/usr/share/info"
-
-  rm "$pkgdir"/usr/lib/bfd-plugins/libdep.so
+  rm -r "$pkgdir"/usr/share/info
 }
-
-# getver: gnu.org/software/binutils
