* update aarch64-linux-gnu-binutils to 2.43-1

diff --git a/cross-compilers/aarch64-linux-gnu-binutils/PKGBUILD b/cross-compilers/aarch64-linux-gnu-binutils/PKGBUILD
--- a/cross-compilers/aarch64-linux-gnu-binutils/PKGBUILD
+++ b/cross-compilers/aarch64-linux-gnu-binutils/PKGBUILD
@@ -1,80 +1,72 @@
 # POWER Maintainer: Alexander Baldeck <alex.bldck@gmail.com>
-# Maintainer: Felix Yan <felixonmars@archlinux.org>
-# Maintainer: Alexander F. Rødseth <xyproto@archlinux.org>
-# Contributor: Emil Renner Berthing <aur@esmil.dk>
+# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>
 
 _target=aarch64-linux-gnu
 pkgname=$_target-binutils
-pkgver=2.42+r91+g6224493e457
-_commit=6224493e457e72b11818c87cdc112bdb0fee5f81
+pkgver=2.43
 pkgrel=1
-pkgdesc='Assemble and manipulate binary and object files for m68k'
+pkgdesc='A set of programs to assemble and manipulate binary and object files for the ARM64 target'
 arch=(x86_64 powerpc64le powerpc64 powerpc riscv64)
-url='https://gnu.org/software/binutils/'
+url='https://www.gnu.org/software/binutils/'
 license=(GPL)
-depends=(glibc zlib libelf jansson)
-makedepends=(git setconf)
-source=(git+https://sourceware.org/git/binutils-gdb.git#commit=${_commit}
-	gold-warn-unsupported.patch)
-sha512sums=('f795d671307315c348b98bfca7b8563ea9a4814c255ad6cee780d75c2f73be8f598b5e187698bad18dcf6eeffbb1aff9cab8d984d33561a3e88dfccaf367b5f9'
-            '5d827b349b4456f8314776f1545396945c751b822a77604157b3fe436e5ff82bb313af3a215c99fd9d1f1f8ebb9f92033cc1a4968e35734619ad28b9bb3839a7')
+depends=(zlib libelf)
+source=(https://ftp.gnu.org/gnu/binutils/binutils-$pkgver.tar.bz2{,.sig})
+sha1sums=('9b0b465bf52fdbb677bd67ba64424842e297ebcd'
+          'SKIP')
+sha256sums=('fed3c3077f0df7a4a1aa47b080b8c53277593ccbb4e5e78b73ffb4e3f265e750'
+            'SKIP')
+validpgpkeys=('3A24BC1E8FB409FA9F14371813FCEF89DD9E3C4F') # Nick Clifton (Chief Binutils Maintainer) <nickc@redhat.com>
 
 prepare() {
-  cd ${srcdir}
-  [[ ! -d binutils-gdb ]] && ln -s binutils-$pkgver binutils-gdb
-
-  cd "binutils-gdb"
-  # Creds @Fedora
-  # Change the gold configuration script to only warn about
-  # unsupported targets.  This allows the binutils to be built with
-  # BPF support enabled.
-  patch -Np1 -i "${srcdir}"/gold-warn-unsupported.patch
-
-  setconf libiberty/configure ac_cpp "'\$CPP \$CPPFLAGS -O2'"
+  cd binutils-$pkgver
+  sed -i "/ac_cpp=/s/\$CPPFLAGS/\$CPPFLAGS -O2/" libiberty/configure
 }
 
 build() {
-  cd "binutils-gdb"
+  cd binutils-$pkgver
 
-  unset CPPFLAGS
-  ./configure \
-    --disable-nls \
-    --enable-deterministic-archives \
-    --enable-gold \
-    --enable-ld=default \
-    --enable-multilib \
-    --enable-plugins \
-    --prefix=/usr \
-    --target=$_target \
-    --with-gnu-as \
-    --with-gnu-ld \
-    --with-sysroot=/usr/$_target/usr \
-    --with-system-zlib \
-    --disable-werror \
-    --disable-sim \
-    --enable-colored-disassembly \
-    --enable-targets=no
+  if [ "${CARCH}" != "i686" ];
+  then
+    # enabling gold linker at i686 makes the install fail
+    enable_gold='--enable-gold'
+  fi
+
+  ./configure --target=$_target \
+              --with-sysroot=/usr/$_target \
+              --prefix=/usr \
+              --disable-multilib \
+              --with-gnu-as \
+              --with-gnu-ld \
+              --disable-nls \
+              --enable-ld=default \
+              $enable_gold \
+              --enable-plugins \
+              --enable-deterministic-archives
+
   make
 }
 
 check() {
-  # * Unset LDFLAGS as testsuite makes assumptions about which ones are active.
-  # * Do not abort on errors - manually check log files.
-  make -C "binutils-gdb" LDFLAGS="" -k check
+  cd binutils-$pkgver
+
+  # unset LDFLAGS as testsuite makes assumptions about which ones are active
+  # do not abort on errors - manually check log files
+  make -k LDFLAGS="" check || true
 }
 
 package() {
-  make -C "binutils-gdb" DESTDIR="$pkgdir" install
+  cd binutils-$pkgver
 
-  install -d -m755 "$pkgdir/usr/$_target/usr"
-  mv $pkgdir/usr/$_target/{bin,lib} "$pkgdir/usr/$_target/usr/"
+  make DESTDIR="$pkgdir" install
+
+  # Remove file conflicting with host binutils and manpages for MS Windows tools
+  rm -fv "$pkgdir"/usr/share/man/man1/$_target-{dlltool,windres,windmc}*
+  rm -fv "$pkgdir"/usr/lib/bfd-plugins/libdep.so
+  rm -fv "$pkgdir"/usr/etc/gprofng.rc
+  rm -fv "$pkgdir"/usr/lib/libgprofng.a
+  rm -frv "$pkgdir"/usr/include
+  rm -frv "$pkgdir"/usr/lib/gprofng/
 
   # Remove info documents that conflict with host version
-  rm -r "$pkgdir/usr/share/info"
-  rm -r "$pkgdir/usr/share/gdb"
-  rm "$pkgdir/usr/include/gdb/jit-reader.h"
-
-  rm "$pkgdir"/usr/lib/bfd-plugins/libdep.so
+  rm -frv "$pkgdir"/usr/share/info
 }
-
-# getver: gnu.org/software/binutils
