* update rust to 1:1.89.0-1

diff --git a/rust/PKGBUILD b/rust/PKGBUILD
--- a/rust/PKGBUILD
+++ b/rust/PKGBUILD
@@ -12,11 +12,12 @@ pkgname=(
   rust-wasm
 )
 epoch=1
-pkgver=1.88.0
+pkgver=1.89.0
 pkgrel=1
 pkgdesc="Systems programming language focused on safety, speed and concurrency"
 url=https://www.rust-lang.org/
-arch=(powerpc64le powerpc64 powerpc espresso)
+#arch=(powerpc64le powerpc64 powerpc espresso)
+arch=(powerpc espresso)
 license=("Apache-2.0 OR MIT")
 options=(
   !emptydirs
@@ -50,23 +51,46 @@ checkdepends=(
 )
 source=(
   "https://static.rust-lang.org/dist/rustc-$pkgver-src.tar.gz"{,.asc}
+  # Patch bootstrap so that rust-analyzer-proc-macro-srv
+  # is in /usr/lib instead of /usr/libexec
   0001-bootstrap-Change-libexec-dir.patch
+
+  # Put bash completions where they belong
   0002-bootstrap-Change-bash-completion-dir.patch
-  0003-bootstrap-Use-lld-mode-only-for-host-linked-targets.patch
-  0004-compiler-Change-LLVM-targets.patch
-  0005-compiler-Use-wasm-ld-for-wasm-targets.patch
+
+  # Use our *-pc-linux-gnu targets, making LTO with clang simpler
+  0003-compiler-Change-LLVM-targets.patch
+
+  # Use our wasm-ld
+  0004-compiler-Use-wasm-ld-for-wasm-targets.patch
+
+  # Use our aarch64-linux-gnu-gcc
+  0005-compiler-Use-aarch64-linux-gnu-gcc-to-link-aarch64-t.patch
+
+  # Prefer "lib" over "lib64"
+  0006-compiler-Swap-primary-and-secondary-lib-dirs.patch
+
+  # Fix build with glibc 2.42
+  0001-compiler-rt-Fix-compilation-with-glibc-2.42.patch
+
+  # Fix build with system rustc
+  # https://github.com/rust-lang/rust/issues/143735
+  0007-bootstrap-Workaround-for-system-stage0.patch
+
+  # ArchPOWER powerpc64 is ELFv2
   hotfix-abi.powerpc64.elfv2.patch
-  powerpc-atomics.patch
 )
-b2sums=('5c672e9cab0c6dd3229efdd63e2d81a728e488c72870db9be306f0fea9078005ca3af74fb1070b19f9610e83b166df5ef4e642340647964ce622edea38b35d61'
+b2sums=('5cc32e9e7f766ec3631f369c1b60d4a9bcb39c21ede5ef6364cccf32d0d4105cab3fd10dfdf5f38db304db0dc771ae783303ed94d6277013770b59ee569a48c1'
         'SKIP'
-        '743bf583cf40ec856b7d89953af53db9ef9e7047b936a60e88e626bb7b389446bc5ed7b8b1d02001131ec728455a77ed78d6eeb64e61c370de81c2fe488836cc'
-        'f39eef3c8dce60f2ecdac5ac169cbe749c8c353241a1c48cf4815f1da37be174007d5efc98574b4865dcaee886b618139d54fc274be92cc8063a9c48f48b985b'
-        '188c7065d8a623396d7ed93c1f2a4188fd46ede9f93e9bd8e933648fc3db0924b68ec78d2f4b29529bbdcc5d809f6711438535e70d153e0131f10273109e162b'
-        '7c919047f50325be6ad5686094c97affe2148f99c5b41748e8e0187674e3b2c0eed10cd3798c866fbd2f65889636f88a439bad0892c093f6bece3f1263c89c30'
+        '17e7f6e73936137507e387cd2761b0b98f9457391e4f534beb872effaa9f442e72351bb39d5e34963d9f18a31fd9f07139cfbde4df9c4c1d8cc6e5d3a7f2c8f7'
+        'fed39e683a0fa4b7730c629f2453bccb70d2b37329ee8853e0c8e8cbc07a227a6c15bdf81c7285a2a2debeffde24ef14abcfccee6383024ac6bff7405e725482'
+        '1f664dc8156ebe48ae49e7651312ca8879b40fb65471bd9e4180e84fc8b2f6e94b50b7ff7db598e8f298058fae7bcc591532fe087084330650c69df131d2bb85'
         '2317343e6b986d1ec1fb6d035fb6d8933245704b5be1b3e4a032ad14300d8a338087c52e53a6dff4ceda52232ce7f21dd8ad536c9d4da04faee6a9b79a9670b6'
-        'a02116ad16a9c9ff03b45a2ba046ab2840649123aab98538ab8416e0a345d27ce5a688317bfaff37a0c1d1e4d004e3dd35876adc5b6309a717537c4322ee2a5b'
-        '88265ab7c10451a5fe47e04dbc0ecff9b471376675c25c0f3b297126387c3f5444be9ce11876e460603a9dfd246eb1a007c260734535b31499ce1803a156d157')
+        '5db7f8a8320e6900c35c0f3db270f70e5ee00b466038914b474ad33a822f20c2e518934dffb2d4391ae8a5ef94b49ab21ef7f57ab86686a51499d9f5516faa94'
+        '8be938ad0016244e86707396ee147fdff7a7ee4d2a776607ff316a9264512faba99d03a7a6b5ba48744c3ae93b09a2eaede567554142a30570346e177131099f'
+        'b9fdc6e4849dd167568322a09c645e1dfbbb4ceb1d6057744fa170c22f29195f3a6a3e6e71807f24124d6c7af659f7a91611f9b1b1f3702ceaba34f1fd153aca'
+        'f7f43c42856be95b658963275f6ebd94a500f24f23c925e3d9e5fe917f6d509bfd75d2fca072c987e93cd7d5a3776800ba633406cd77fe387b39252b5b7dfbc2'
+        'a9ae4c261f0ce97500c038102a2eae37f868313c0d95ebcc9644cb5d4c9e16cb9b1079f698857afad6ade7962d6c8b5297688087f188c04fe0c4d159bde8141a')
 validpgpkeys=(
   108F66205EAEB0AAA8DD5E1C85AB96E6FA1BE5FE  # Rust Language (Tag and Release Signing Key) <rust-key@rust-lang.org>
 )
@@ -77,40 +101,26 @@ COMPRESSZST+=(--long)
 prepare() {
   cd rustc-$pkgver-src
 
-  # Patch bootstrap so that rust-analyzer-proc-macro-srv
-  # is in /usr/lib instead of /usr/libexec
-  patch -Np1 -i ../0001-bootstrap-Change-libexec-dir.patch
+  local src
+  for src in "${source[@]}"; do
+    src="${src%%::*}"
+    src="${src##*/}"
+    src="${src%.zst}"
+    [[ $src = *.patch ]] || continue
+    echo "Applying patch $src..."
+    patch -Np1 < "../$src"
+  done
 
-  # Put bash completions where they belong
-  patch -Np1 -i ../0002-bootstrap-Change-bash-completion-dir.patch
-
-  # Unbreak wasm targets
-  patch -Np1 -i ../0003-bootstrap-Use-lld-mode-only-for-host-linked-targets.patch
-
-  # Use our *-pc-linux-gnu targets, making LTO with clang simpler
-  patch -Np1 -i ../0004-compiler-Change-LLVM-targets.patch
-
-  # Use our wasm-ld
-  patch -Np1 -i ../0005-compiler-Use-wasm-ld-for-wasm-targets.patch
-
-  # powerpc64 elfv2
-  patch -Np1 -i ../hotfix-abi.powerpc64.elfv2.patch 
-
-  # powerpc stuff
-  patch -Np1 -i ../powerpc-atomics.patch
+  sed -i 's/\("files":{[^,]*\),[^}]*}/\1}/' vendor/*/.cargo-checksum.json
 
   _rust_target="\"${CHOST}\""
+
+  _lto="fat"
   case "${CARCH}" in
-    powerpc)
-      # fails to link with -O3 due to 32bit related relocation problems
-      export RUSTFLAGS="-C opt-level=1"
-    ;;
-    riscv64)
-      _rust_target='"riscv64gc-unknown-linux-gnu"'
-    ;;
+    powerpc) _lto="off" ;;
   esac
 
-  cat >config.toml <<END
+  cat >bootstrap.toml <<END
 # see src/bootstrap/defaults/
 profile = "dist"
 
@@ -118,8 +128,8 @@ profile = "dist"
 change-id = 140732
 
 [llvm]
-download-ci-llvm = false
-link-shared = true
+download-ci-llvm = true
+#link-shared = false
 
 [build]
 target = [
@@ -128,8 +138,10 @@ target = [
   "wasm32-wasip1",
   "wasm32-wasip1-threads",
   "wasm32-wasip2",
+  "wasm32v1-none"
 ]
 cargo = "/usr/bin/cargo"
+description = "Arch POWER $pkgbase $epoch:$pkgver-$pkgrel"
 rustc = "/usr/bin/rustc"
 rustfmt = "/usr/bin/rustfmt"
 locked-deps = true
@@ -142,7 +154,6 @@ tools = [
   "rust-analyzer-proc-macro-srv",
   "analysis",
   "src",
-  "rust-demangler",
 ]
 sanitizers = true
 profiler = true
@@ -154,28 +165,33 @@ docs = false
 prefix = "/usr"
 
 [rust]
-debuginfo-level = 1
-debuginfo-level-std = 2
+codegen-units = 1
+codegen-units-std = 1
+#debuginfo-level = 2
+#debuginfo-level-std = 2
 channel = "stable"
-description = "Arch POWER $pkgbase $epoch:$pkgver-$pkgrel"
 rpath = false
 frame-pointers = true
 lld = false
-use-lld = "external"
+#use-lld = "external"
 llvm-bitcode-linker = false
 deny-warnings = false
 backtrace-on-ice = true
 jemalloc = false
+remap-debuginfo = false
+lto = "${_lto}"
 
 [dist]
 compression-formats = ["gz"]
+compression-profile = "fast"
 
 [target.${_rust_target}]
-cc = "/usr/bin/gcc"
-cxx = "/usr/bin/g++"
-ar = "/usr/bin/gcc-ar"
-ranlib = "/usr/bin/gcc-ranlib"
-llvm-config = "/usr/bin/llvm-config"
+cc = "/usr/bin/${CHOST}-gcc"
+cxx = "/usr/bin/${CHOST}-g++"
+ar = "/usr/bin/${CHOST}-gcc-ar"
+ranlib = "/usr/bin/${CHOST}-gcc-ranlib"
+#llvm-config = "/usr/bin/llvm-config"
+linker = "${CHOST}-gcc"
 
 [target.wasm32-unknown-unknown]
 cc = "/usr/bin/clang"
@@ -183,6 +199,17 @@ cxx = "/usr/bin/clang++"
 ar = "/usr/bin/llvm-ar"
 ranlib = "/usr/bin/llvm-ranlib"
 linker = "/usr/bin/wasm-ld"
+default-linker = "wasm-ld"
+sanitizers = false
+profiler = false
+
+[target.wasm32v1-none]
+cc = "/usr/bin/clang"
+cxx = "/usr/bin/clang++"
+ar = "/usr/bin/llvm-ar"
+ranlib = "/usr/bin/llvm-ranlib"
+linker = "/usr/bin/wasm-ld"
+default-linker = "wasm-ld"
 sanitizers = false
 profiler = false
 
@@ -192,6 +219,7 @@ cxx = "/usr/bin/clang++"
 ar = "/usr/bin/llvm-ar"
 ranlib = "/usr/bin/llvm-ranlib"
 linker = "/usr/bin/wasm-ld"
+default-linker = "wasm-ld"
 sanitizers = false
 profiler = false
 wasi-root = "/usr/share/wasi-sysroot"
@@ -202,6 +230,7 @@ cxx = "/usr/bin/clang++"
 ar = "/usr/bin/llvm-ar"
 ranlib = "/usr/bin/llvm-ranlib"
 linker = "/usr/bin/wasm-ld"
+default-linker = "wasm-ld"
 sanitizers = false
 profiler = false
 wasi-root = "/usr/share/wasi-sysroot"
@@ -212,6 +241,7 @@ cxx = "/usr/bin/clang++"
 ar = "/usr/bin/llvm-ar"
 ranlib = "/usr/bin/llvm-ranlib"
 linker = "/usr/bin/wasm-ld"
+default-linker = "wasm-ld"
 sanitizers = false
 profiler = false
 wasi-root = "/usr/share/wasi-sysroot"
@@ -221,7 +251,7 @@ END
 _pick() {
   local p="$1" f d; shift
   for f; do
-    d="$srcdir/$p/$f"
+    d="$srcdir/$p/${f#$pkgdir/}"
     mkdir -p "$(dirname "$d")"
     mv "$f" "$d"
     rmdir -p --ignore-fail-on-non-empty "$(dirname "$f")"
@@ -229,9 +259,19 @@ _pick() {
 }
 
 build() {
+  #rustup toolchain update --profile default 1.88.0
+  #rustup default 1.88.0
+
+  case "${CARCH}" in
+    powerpc)
+      # fails to link with -O3 due to 32bit related relocation problems
+      export RUSTFLAGS="-C opt-level=1"
+    ;;
+  esac
+
   cd rustc-$pkgver-src
 
-  export RUST_BACKTRACE=1
+  export RUST_BACKTRACE=full
   unset CFLAGS CXXFLAGS LDFLAGS
 
   DESTDIR="$srcdir/dest-rust" python ./x.py install -j "$(nproc)"
@@ -255,7 +295,7 @@ build() {
   done
 
   _pick dest-src  usr/lib/rustlib/src
-  _pick dest-wasm usr/lib/rustlib/wasm32-*
+  _pick dest-wasm usr/lib/rustlib/wasm32{,v1}-*
 }
 
 package_rust() {
